name: sipelajar
version: 1.0.3+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  package_info_plus: ^1.4.2
  flutter_downloader: ^1.8.0+1
  app_installer: ^1.1.0
  get_storage: ^2.0.3
  http: ^0.13.4
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  fluttertoast: ^8.0.9
  flutter_spinkit: ^5.1.0
  permission_handler: ^10.0.0
  open_file: ^3.2.1
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  connectivity: ^3.0.6
  path: ^1.8.1
  camera: ^0.10.0
  flutter_map_arcgis: ^2.0.0
  flutter_map: ^0.14.0
  dio: ^4.0.6
  latlong2: ^0.8.1
  geocoding: ^2.0.4
  map_launcher: ^2.2.3
  flutter:
    sdk: flutter
  flutter_map_location_marker: ^3.1.0
  http_parser: ^4.0.1
  geolocator: ^8.2.1
  firebase_messaging: ^12.0.0
  firebase_core: ^1.19.2
  flutter_local_notifications: ^9.7.0
  flutter_html: ^3.0.0-alpha.5
  restart_app: ^1.1.0+1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.4

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/sounds/
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo-app.png"

flutter_native_splash:
  background_image: "assets/images/bg_login.png"
  image: "assets/images/splash.png"
